/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.ProdutosDAO;
import DAO.VendaDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Evandro Teruel
 */
public class TelaInicial extends javax.swing.JFrame {
    
    DefaultTableModel defTable;
    /**
     * Creates new form TelaRelatorios
     */
    public TelaInicial() {
        initComponents();
        defTable = (DefaultTableModel) tblProdutos.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTipoRelatorio = new javax.swing.JLabel();
        cmbTipoRelatorio = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        btnVenda = new javax.swing.JButton();
        btnManiProd = new javax.swing.JButton();

        setTitle("Relatórios de produtos");
        getContentPane().setLayout(null);

        lblTipoRelatorio.setText("Tipo de Relatório");
        getContentPane().add(lblTipoRelatorio);
        lblTipoRelatorio.setBounds(10, 10, 120, 50);

        cmbTipoRelatorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produtos", "Vendas" }));
        cmbTipoRelatorio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoRelatorioItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbTipoRelatorio);
        cmbTipoRelatorio.setBounds(130, 22, 160, 30);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(590, 20, 140, 30);

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Informaçao", "Valor"
            }
        ));
        jScrollPane1.setViewportView(tblProdutos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 710, 330);

        btnVenda.setText("Vendas");
        btnVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendaActionPerformed(evt);
            }
        });
        getContentPane().add(btnVenda);
        btnVenda.setBounds(540, 410, 180, 30);

        btnManiProd.setText("Manipulaçao de produtos");
        btnManiProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManiProdActionPerformed(evt);
            }
        });
        getContentPane().add(btnManiProd);
        btnManiProd.setBounds(50, 415, 180, 30);

        setSize(new java.awt.Dimension(766, 495));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //1 - Pegar o conteúdo do combo de tipo de relatório
        String tipoRelatorio;
        tipoRelatorio = cmbTipoRelatorio.getSelectedItem().toString();
        
        
        boolean resposta;
 
            //2 - Conectar com o Banco de dados
            if (tipoRelatorio.equalsIgnoreCase("Produtos")) {
                
                ProdutosDAO dao = new ProdutosDAO();
                resposta = dao.conectar();
                if(resposta){
                    ArrayList<Object> resultado = dao.consultartudo();

                    defTable.setRowCount(0);
                    for(int i = 0;i < resultado.size(); i++){
                        defTable.addRow((Object[]) resultado.get(i));
                    }
                }
                
            } else if (tipoRelatorio.equalsIgnoreCase("Vendas")) {
                
                VendaDAO dao = new VendaDAO();
                resposta = dao.conectar();
                if(resposta){
                    ArrayList<Object> resultado = dao.consultartudo();
                
                defTable.setRowCount(0);
                resultado.forEach(a ->{
                    defTable.addRow((Object[]) a);
                });
                }
                
            }
      
        
       
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cmbTipoRelatorioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoRelatorioItemStateChanged
        String tipo;
        tipo = cmbTipoRelatorio.getSelectedItem().toString();
        if(tipo.equalsIgnoreCase("Produtos")){
            defTable.setRowCount(0);
        }else if(tipo.equalsIgnoreCase("Vendas")){

            defTable.setRowCount(0);
        }
    }//GEN-LAST:event_cmbTipoRelatorioItemStateChanged

    private void btnVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaActionPerformed
        TelaVenda tela;
        tela = new TelaVenda();
        tela.setVisible(true);
    }//GEN-LAST:event_btnVendaActionPerformed

    private void btnManiProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManiProdActionPerformed
        TelaProdutos tela;
        tela = new TelaProdutos();
        tela.setVisible(true);
    }//GEN-LAST:event_btnManiProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnManiProd;
    private javax.swing.JButton btnVenda;
    private javax.swing.JComboBox<String> cmbTipoRelatorio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTipoRelatorio;
    private javax.swing.JTable tblProdutos;
    // End of variables declaration//GEN-END:variables
}
