package View;

import DAO.Produto;
import DAO.ProdutosDAO;
import DAO.VendaDAO;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

public class TelaProdutos extends javax.swing.JFrame {

    public TelaProdutos() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSaudacao = new javax.swing.JLabel();
        pnlCadastrarProdutos = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setTitle("Menu");
        getContentPane().setLayout(null);

        lblSaudacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblSaudacao);
        lblSaudacao.setBounds(470, 0, 220, 30);

        pnlCadastrarProdutos.setLayout(null);

        lblCodigo.setText("Código");
        pnlCadastrarProdutos.add(lblCodigo);
        lblCodigo.setBounds(20, 20, 70, 20);
        pnlCadastrarProdutos.add(txtCodigo);
        txtCodigo.setBounds(110, 10, 170, 40);

        lblNome.setText("Nome");
        pnlCadastrarProdutos.add(lblNome);
        lblNome.setBounds(20, 70, 70, 20);
        pnlCadastrarProdutos.add(txtNome);
        txtNome.setBounds(110, 60, 320, 40);

        lblCategoria.setText("Quantidade");
        pnlCadastrarProdutos.add(lblCategoria);
        lblCategoria.setBounds(20, 120, 70, 20);
        pnlCadastrarProdutos.add(txtQuantidade);
        txtQuantidade.setBounds(110, 110, 150, 40);

        lblPreco.setText("Preço");
        pnlCadastrarProdutos.add(lblPreco);
        lblPreco.setBounds(20, 170, 70, 20);
        pnlCadastrarProdutos.add(txtPreco);
        txtPreco.setBounds(110, 160, 150, 40);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnlCadastrarProdutos.add(btnSalvar);
        btnSalvar.setBounds(20, 220, 150, 40);

        btnConsultar.setText("Buscar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        pnlCadastrarProdutos.add(btnConsultar);
        btnConsultar.setBounds(290, 10, 100, 40);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        pnlCadastrarProdutos.add(btnExcluir);
        btnExcluir.setBounds(180, 220, 140, 40);

        btnAlterar.setText("Salvar alteração");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        pnlCadastrarProdutos.add(btnAlterar);
        btnAlterar.setBounds(340, 220, 140, 40);

        getContentPane().add(pnlCadastrarProdutos);
        pnlCadastrarProdutos.setBounds(20, 50, 670, 270);
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 720, 400);

        setSize(new java.awt.Dimension(758, 454));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        ProdutosDAO dao = new ProdutosDAO();
        boolean resposta = dao.conectar();
        if(resposta){
            Produto p = new Produto();
            p.setNome(txtNome.getText());
            p.setPreco(Double.parseDouble(txtPreco.getText()));
            p.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
            dao.salvar(p);
            txtCodigo.setText("");
            txtNome.setText("");
            txtQuantidade.setText("");
            txtPreco.setText("");
            txtCodigo.requestFocus();
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if (txtCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o código do produto");
            txtCodigo.requestFocus();
            return; // para a execução nesta linha (stop)       
        }
        ProdutosDAO dao = new ProdutosDAO();
        boolean resposta = dao.conectar();
        if(resposta){
            Produto p = dao.consultar(Integer.parseInt(txtCodigo.getText()));
            if(p != null){
                txtNome.setText(p.getNome());
                txtQuantidade.setText(String.valueOf(p.getQuantidade()));
                txtPreco.setText(String.valueOf(p.getPreco()));
                btnExcluir.setVisible(true);
                btnAlterar.setVisible(true);
            } else { //Senão encontrou o produto
                JOptionPane.showMessageDialog(null, "Produto não encontrado");
                txtCodigo.requestFocus();
            }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        ProdutosDAO dao = new ProdutosDAO();
        boolean resposta = dao.conectar();
        if(resposta){
            boolean res = dao.excluir(Integer.parseInt(txtCodigo.getText()));
            if(res){
                JOptionPane.showMessageDialog(null, "Produto excluído com sucesso");
                txtCodigo.setText("");
                txtNome.setText("");
                txtQuantidade.setText("");
                txtPreco.setText("");
                txtCodigo.requestFocus();
                btnExcluir.setVisible(false);
                btnAlterar.setVisible(false);
            }else { // Se não excluiu da tabela
                JOptionPane.showMessageDialog(null, "Não foi possível excluir o produto com este código");
            }
        }     

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        ProdutosDAO dao = new ProdutosDAO();
        boolean resposta = dao.conectar();
        if(resposta){
            dao.alterar(txtCodigo.getText(), txtNome.getText(), txtQuantidade.getText(), txtPreco.getText());
        }
            JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso");
            txtCodigo.setText("");
            txtNome.setText("");
            txtQuantidade.setText("");
            txtPreco.setText("");
            txtCodigo.requestFocus();
            btnExcluir.setVisible(false);
            btnAlterar.setVisible(false);
        

    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblSaudacao;
    private javax.swing.JPanel pnlCadastrarProdutos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
