
package View;
import Service.VendaService;
import javax.swing.JOptionPane;



public class TelaVenda extends javax.swing.JFrame {

 
    public TelaVenda() {
        initComponents();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMatricula = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtQuant = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de funcionários");
        getContentPane().setLayout(null);

        lblMatricula.setText("Codigo do Produto");
        getContentPane().add(lblMatricula);
        lblMatricula.setBounds(20, 30, 90, 30);
        getContentPane().add(txtCod);
        txtCod.setBounds(120, 30, 240, 30);

        lblNome.setText("Quantidade");
        getContentPane().add(lblNome);
        lblNome.setBounds(30, 90, 80, 30);
        getContentPane().add(txtQuant);
        txtQuant.setBounds(120, 90, 240, 30);

        btnSalvar.setText("Executar Venda");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(160, 160, 130, 30);

        setSize(new java.awt.Dimension(559, 276));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        boolean salvarVenda = VendaService.ComputarVenda(Integer.parseInt(txtCod.getText()),
                Integer.parseInt(txtQuant.getText()));
        if (salvarVenda == false) {
            JOptionPane.showMessageDialog(null, "Nao foi possivel computar esta venda");
            return;
        }else{
            
            limpar();
        }
  
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void limpar() {
        txtCod.setText("");
        txtQuant.setText("");
        txtCod.requestFocus();       
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtQuant;
    // End of variables declaration//GEN-END:variables
}
